"""
===============================================================================
Project      : AI Research Assistant
File         : report.py
Version      : 1.0.0
Author       : Dr. B. Sudhakar

Description:
Report page for displaying a completed AI research paper analysis.

Responsibilities:
    - Display a previously generated analysis report.
    - Display paper metadata.
    - Display AI-generated analysis.

Business logic must not be implemented in this module.
===============================================================================
"""

from __future__ import annotations

import streamlit as st

from app.models.analysis_record import AnalysisRecord


def show_report_page() -> None:
    """
    Render the Analysis Report page.
    """

    st.title("📑 Analysis Report")

    record: AnalysisRecord | None = st.session_state.get(
        "analysis_record"
    )

    if record is None:
        st.info(
            "No analysis report is available.\n\n"
            "Analyze a research paper or open a report from the "
            "History page."
        )
        return

    st.success("Analysis report loaded successfully.")

    st.divider()

    st.subheader("Paper Information")

    st.write(f"**Title:** {record.title}")
    st.write(f"**Filename:** {record.filename}")

    col1, col2 = st.columns(2)

    with col1:
        st.metric("Pages", record.total_pages)
        st.metric("Characters", record.total_characters)
        st.metric("Analysis Type", record.analysis_type)

    with col2:
        st.metric("Provider", record.provider)
        st.metric("Model", record.model)
        st.metric(
            "Execution Time",
            f"{record.execution_time:.2f} sec",
        )

    st.divider()

    st.subheader("AI Analysis")

    st.markdown(record.analysis)

    st.divider()

    st.caption(
        "Report generated by AI Research Assistant."
    )