from __future__ import annotations

import re
from html import escape
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer

from app.config.branding import get_brand_config
from app.models.research_project import ResearchProposal


def render_proposal_markdown(proposal: ResearchProposal) -> str:
    brand = get_brand_config()
    return (
        f"{proposal.content}\n\n---\n"
        f"Generated by **{brand.application_name}** · {brand.credit}\n"
        f"Proposal version: {proposal.version} · Provider: {proposal.provider} · Model: {proposal.model}\n"
    )


def render_proposal_html(proposal: ResearchProposal) -> str:
    body = escape(proposal.content)
    body = re.sub(r"^### (.+)$", r"<h3>\1</h3>", body, flags=re.MULTILINE)
    body = re.sub(r"^## (.+)$", r"<h2>\1</h2>", body, flags=re.MULTILINE)
    body = re.sub(r"^# (.+)$", r"<h1>\1</h1>", body, flags=re.MULTILINE)
    body = body.replace("\n", "<br>\n")
    brand = get_brand_config()
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>{escape(proposal.title)}</title>
<style>body{{font:16px/1.6 Arial;max-width:900px;margin:40px auto;color:#172554}}h1,h2{{color:#173b8f}}
header,footer{{padding:18px;background:#eef2ff;border-radius:12px}}footer{{margin-top:32px;font-size:13px}}</style></head>
<body><header><strong>{escape(brand.application_name)}</strong><br>{escape(brand.tagline)}</header>
<main>{body}</main><footer>Version {proposal.version} · {escape(brand.credit)}</footer></body></html>"""


def render_proposal_pdf(proposal: ResearchProposal) -> bytes:
    brand = get_brand_config()
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4, rightMargin=20 * mm, leftMargin=20 * mm,
        topMargin=25 * mm, bottomMargin=22 * mm,
        title=proposal.title, author=brand.author,
    )
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ProposalTitle", parent=styles["Title"],
                              textColor=colors.HexColor("#173B8F"), alignment=TA_CENTER,
                              fontSize=19, leading=24, spaceAfter=12))
    styles.add(ParagraphStyle(name="Section2", parent=styles["Heading2"],
                              textColor=colors.HexColor("#173B8F"), spaceBefore=12,
                              spaceAfter=6, keepWithNext=True))
    styles.add(ParagraphStyle(name="ProposalBody", parent=styles["BodyText"],
                              fontSize=10.2, leading=15, spaceAfter=6))
    story = [Paragraph(escape(brand.application_name), styles["Heading3"]),
             Paragraph(escape(proposal.title), styles["ProposalTitle"]),
             Paragraph(escape(f"{proposal.proposal_type} - Version {proposal.version}"), styles["Italic"]),
             Spacer(1, 8)]
    for raw in proposal.content.splitlines():
        line = raw.strip()
        if not line:
            story.append(Spacer(1, 5))
        elif line.startswith("## "):
            story.append(Paragraph(escape(line[3:]), styles["Section2"]))
        elif line.startswith("# "):
            continue
        elif line.startswith(('- ', '* ')):
            story.append(Paragraph("- " + escape(line[2:]), styles["ProposalBody"]))
        else:
            clean = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", escape(line))
            story.append(Paragraph(clean, styles["ProposalBody"]))

    def decorate(canvas, document):
        canvas.saveState()
        canvas.setStrokeColor(colors.HexColor("#CBD5E1"))
        if document.page > 1:
            canvas.setFont("Helvetica-Bold", 8)
            canvas.setFillColor(colors.HexColor("#173B8F"))
            canvas.drawString(20 * mm, 286 * mm, brand.application_name)
            canvas.setStrokeColor(colors.HexColor("#CBD5E1"))
            canvas.line(20 * mm, 282 * mm, 190 * mm, 282 * mm)
        canvas.line(20 * mm, 16 * mm, 190 * mm, 16 * mm)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#64748B"))
        canvas.drawString(20 * mm, 10 * mm, brand.credit)
        canvas.drawRightString(190 * mm, 10 * mm, f"Page {document.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=decorate, onLaterPages=decorate)
    return buffer.getvalue()
